/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.16
 * Generated at: 2017-07-21 03:03:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.seat;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import work.model.dao.*;
import work.model.dto.*;
import work.controller.*;

public final class seatStart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("work.controller");
    _jspx_imports_packages.add("work.model.dao");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("work.model.dto");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>좌석배정시스템</title>\r\n");

		SeatDao dao = new SeatDao();
		ArrayList<Seat> list = dao.selectList();

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\tfunction payCount1(){\r\n");
      out.write("\t\tdocument.payForm.totalCost.value=1000;\r\n");
      out.write("\t\tdocument.payForm.remainCost.value=1000;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction payCount2(){\r\n");
      out.write("\t\tdocument.payForm.totalCost.value=2000;\r\n");
      out.write("\t\tdocument.payForm.remainCost.value=2000;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction payCount3(){\r\n");
      out.write("\t\tdocument.payForm.totalCost.value=3000;\r\n");
      out.write("\t\tdocument.payForm.remainCost.value=3000;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction payCount5(){\r\n");
      out.write("\t\tdocument.payForm.totalCost.value=5000;\r\n");
      out.write("\t\tdocument.payForm.remainCost.value=5000;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction payCount8(){\r\n");
      out.write("\t\tdocument.payForm.totalCost.value=8000;\r\n");
      out.write("\t\tdocument.payForm.remainCost.value=8000;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction payCount10(){\r\n");
      out.write("\t\tdocument.payForm.totalCost.value=10000;\r\n");
      out.write("\t\tdocument.payForm.remainCost.value=10000;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction insertSeatNo1(){\r\n");
      out.write("\t\tdocument.payForm.seatNo.value=1;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction insertSeatNo2(){\r\n");
      out.write("\t\tdocument.payForm.seatNo.value=2;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction insertSeatNo3(){\r\n");
      out.write("\t\tdocument.payForm.seatNo.value=3;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction insertSeatNo4(){\r\n");
      out.write("\t\tdocument.payForm.seatNo.value=4;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction insertSeatNo5(){\r\n");
      out.write("\t\tdocument.payForm.seatNo.value=5;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction insertSeatNo6(){\r\n");
      out.write("\t\tdocument.payForm.seatNo.value=6;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction insertSeatNo7(){\r\n");
      out.write("\t\tdocument.payForm.seatNo.value=7;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction insertSeatNo8(){\r\n");
      out.write("\t\tdocument.payForm.seatNo.value=8;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction insertSeatNo9(){\r\n");
      out.write("\t\tdocument.payForm.seatNo.value=9;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction insertSeatNo10(){\r\n");
      out.write("\t\tdocument.payForm.seatNo.value=10;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction insertSeatNo11(){\r\n");
      out.write("\t\tdocument.payForm.seatNo.value=11;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction insertSeatNo12(){\r\n");
      out.write("\t\tdocument.payForm.seatNo.value=12;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction insertSeatNo13(){\r\n");
      out.write("\t\tdocument.payForm.seatNo.value=13;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction insertSeatNo14(){\r\n");
      out.write("\t\tdocument.payForm.seatNo.value=14;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction insertSeatNo15(){\r\n");
      out.write("\t\tdocument.payForm.seatNo.value=15;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction insertSeatNo16(){\r\n");
      out.write("\t\tdocument.payForm.seatNo.value=16;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction insertSeatNo17(){\r\n");
      out.write("\t\tdocument.payForm.seatNo.value=17;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction insertSeatNo18(){\r\n");
      out.write("\t\tdocument.payForm.seatNo.value=18;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction insertSeatNo19(){\r\n");
      out.write("\t\tdocument.payForm.seatNo.value=19;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction insertSeatNo20(){\r\n");
      out.write("\t\tdocument.payForm.seatNo.value=20;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction insertSeatNo21(){\r\n");
      out.write("\t\tdocument.payForm.seatNo.value=21;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction insertSeatNo22(){\r\n");
      out.write("\t\tdocument.payForm.seatNo.value=22;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction insertSeatNo23(){\r\n");
      out.write("\t\tdocument.payForm.seatNo.value=23;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction insertSeatNo24(){\r\n");
      out.write("\t\tdocument.payForm.seatNo.value=24;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction insertSeatNo25(){\r\n");
      out.write("\t\tdocument.payForm.seatNo.value=25;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction insertSeatNo26(){\r\n");
      out.write("\t\tdocument.payForm.seatNo.value=26;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction insertSeatNo27(){\r\n");
      out.write("\t\tdocument.payForm.seatNo.value=27;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction insertSeatNo28(){\r\n");
      out.write("\t\tdocument.payForm.seatNo.value=28;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction insertSeatNo29(){\r\n");
      out.write("\t\tdocument.payForm.seatNo.value=29;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction insertSeatNo30(){\r\n");
      out.write("\t\tdocument.payForm.seatNo.value=30;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction insertMoney(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar insertCost = Number(document.payForm.insertCost.value);\r\n");
      out.write("\t\tinsertCost+=1000;\r\n");
      out.write("\t\tdocument.payForm.insertCost.value=insertCost;\r\n");
      out.write("\t\tdocument.payForm.remainCost.value-=1000;\r\n");
      out.write("\t\tif(document.payForm.remainCost.value==0){\r\n");
      out.write("\t\t\talert(\"결제버튼을 눌러주세요\");\r\n");
      out.write("\t\t\tdocument.getElementById(\"insert\").disabled = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"css/common.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h2 align=\"center\">좌석배정시스템</h2><p>\r\n");

	int onNumber = dao.onNumber();
	int offNumber = dao.offNumber();

      out.write("\r\n");
      out.write("<table width=\"1200px\" border=\"1\">\r\n");
      out.write("\t<tr width=\"1200px\">\r\n");
      out.write("\t\t<td width=\"600px\" align=\"center\">사용가능좌석 : ");
      out.print(onNumber);
      out.write("</td>\r\n");
      out.write("\t\t<td width=\"600px\" align=\"center\">빈좌석 : ");
      out.print(offNumber);
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<hr>\r\n");
      out.write("<form id=\"payForm\" name=\"payForm\" action=\"/pcm/seatcontroller?action=payCharge\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\t<table width=\"1200px\"  border=\"1\" height=\"800px\">\r\n");
      out.write("\t\t<tr width= \"1200px\">\r\n");
      out.write("\t\t\t<td align =\"center\" valign=\"middle\" width=\"300\">\r\n");
      out.write("\t\t\t\t\t\t<table width=\"300\" height=\"650\" >\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\" height=\"50\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"150px\" height=\"150px\" bordercolor=\"write\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<IMG SRC=\"seatImg/cal01.jpg\" align=\"center\"  width=\"150px\" height=\"150px\" onclick =\"payCount1()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"150px\" height=\"150px\" bordercolor=\"write\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<IMG SRC=\"seatImg/cal02.jpg\" align=\"center\"  width=\"150px\" height=\"150px\" onclick=\"payCount2()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\" height=\"50\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"150px\" height=\"150px\" bordercolor=\"write\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<IMG SRC=\"seatImg/cal03.jpg\" align=\"center\"  width=\"150px\" height=\"150px\"onclick=\"payCount3()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"150px\" height=\"150px\" bordercolor=\"write\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<IMG SRC=\"seatImg/cal04.jpg\" align=\"center\"  width=\"150px\" height=\"150px\" onclick=\"payCount5()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\" height=\"50\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"150px\" height=\"150px\" bordercolor=\"write\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<IMG SRC=\"seatImg/cal05.jpg\" align=\"center\"  width=\"150px\",height=\"150px\" onclick=\"payCount8()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"150px\" height=\"150px\" bordercolor=\"write\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<IMG SRC=\"seatImg/cal06.jpg\" align=\"center\"  width=\"150px\",height=\"150px\" onclick=\"payCount10()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\" height=\"50\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td align =\"center\" valign=\"middle\" width=\"300px\">\r\n");
      out.write("\t\t\t\t<table height=\"650px\" width=\"300px\">\r\n");
      out.write("\t\t\t\t\t<tr  height=\"50px\">\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<h2  align=\"center\" >결제화면</h2>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><h3>\r\n");
      out.write("\t\t\t\t\t\t\t아이디 : <input type=\"text\" id=\"memberId\" name=\"memberId\" placeholder=\"아이디를입력하세요\"><br>\r\n");
      out.write("\t\t\t\t\t\t\t좌석번호 : <input type=\"text\" id=\"seatNo\" name=\"seatNo\" placeholder=\"좌석번호를 클릭해주세요\" readonly><br><br><br>\r\n");
      out.write("\t\t\t\t\t\t\t투입금액 : <input type=\"text\" id=\"insertCost\" name=\"insertCost\" readonly>  원<br><br>\r\n");
      out.write("\t\t\t\t\t\t\t남은금액 : <input type=\"text\" id=\"remainCost\" name=\"remainCost\" readonly> 원<br><br>\r\n");
      out.write("\t\t\t\t\t\t\t총금액   : <input type=\"text\" id=\"totalCost\" name=\"totalCost\" readonly> 원<br><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" value = \"1000원투입\" align=\"left\" id=\"insert\" onclick=\"insertMoney()\">\r\n");
      out.write("\t\t\t\t\t\t</h3><td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t <input type=\"submit\" value=\"결제\" >\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 좌석 -->\r\n");
      out.write("\t\t\t<td align =\"center\" valign=\"middle\" width=\"600px\" height=\"650px\">\r\n");
      out.write("\t\t\t<table width=\"600px\" height=\"120px\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"5\" height =\"100px\">\r\n");
      out.write("\t\t\t\t\t\t<table border=\"1\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"300px\" height=\"50px\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<IMG SRC=\"seatImg/on.jpg\" id =\"seat30\"  width=\"50px\" height=\"30px\">사용중\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"300px\" height=\"120px\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<IMG SRC=\"seatImg/off.jpg\" id =\"seat30\"  width=\"50px\" height=\"30px\">사용가능\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"120px\" height=\"113px\">\r\n");
      out.write("\t\t\t\t\t");
	if (list.get(0).getCondition() == 1) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/onseat01.jpg\" id =\"seat01\" align=\"center\"  width=\"120px\" height=\"113px\" onclick =\"insertSeatNo1()\">\r\n");
      out.write("\t\t\t\t\t");
	} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/offseat01.jpg\" id =\"seat01\" align=\"center\"  width=\"120px\" height=\"113px\"onclick =\"insertSeatNo1()\">\r\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"120px\" height=\"113px\">\r\n");
      out.write("\t\t\t\t\t");
	if (list.get(1).getCondition() == 1) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/onseat02.jpg\" id =\"seat02\" align=\"center\"  width=\"120px\" height=\"113px\" onclick =\"insertSeatNo2()\">\r\n");
      out.write("\t\t\t\t\t");
	} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/offseat02.jpg\" id =\"seat02\" align=\"center\"  width=\"120px\" height=\"113px\" onclick =\"insertSeatNo2()\">\r\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"120px\" height=\"113px\">\r\n");
      out.write("\t\t\t\t\t");
	if (list.get(2).getCondition() == 1) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/onseat03.jpg\" id =\"seat03\" align=\"center\"  width=\"120px\" height=\"113px\" onclick =\"insertSeatNo3()\">\r\n");
      out.write("\t\t\t\t\t");
	} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/offseat03.jpg\" id =\"seat03\" align=\"center\"  width=\"120px\" height=\"113px\" onclick =\"insertSeatNo3()\">\r\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"120px\" height=\"113px\">\r\n");
      out.write("\t\t\t\t\t");
	if (list.get(3).getCondition() == 1) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/onseat04.jpg\" id =\"seat04\" align=\"center\"  width=\"120px\" height=\"113px\" onclick =\"insertSeatNo4()\">\r\n");
      out.write("\t\t\t\t\t");
	} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/offseat04.jpg\" id =\"seat04\" align=\"center\"  width=\"120px\" height=\"113px\"  onclick =\"insertSeatNo4()\">\r\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"120px\" height=\"113px\">\r\n");
      out.write("\t\t\t\t\t");
	if (list.get(4).getCondition() == 1) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/onseat05.jpg\" id =\"seat05\" align=\"center\"  width=\"120px\" height=\"113px\"  onclick =\"insertSeatNo5()\">\r\n");
      out.write("\t\t\t\t\t");
	} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/offseat05.jpg\" id =\"seat05\" align=\"center\"  width=\"120px\" height=\"113px\" onclick =\"insertSeatNo5()\">\r\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"120px\" height=\"113px\">\r\n");
      out.write("\t\t\t\t\t");
	if (list.get(5).getCondition() == 1) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/onseat06.jpg\" id =\"seat06\" align=\"center\"  width=\"120px\" height=\"113px\" onclick =\"insertSeatNo6()\">\r\n");
      out.write("\t\t\t\t\t");
	} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/offseat06.jpg\" id =\"seat06\" align=\"center\"  width=\"120px\" height=\"113px\"  onclick =\"insertSeatNo6()\">\r\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"120px\" height=\"113px\">\r\n");
      out.write("\t\t\t\t\t");
	if (list.get(6).getCondition() == 1) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/onseat07.jpg\" id =\"seat07\" align=\"center\"  width=\"120px\" height=\"113px\"  onclick =\"insertSeatNo7()\">\r\n");
      out.write("\t\t\t\t\t");
	} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/offseat07.jpg\" id =\"seat07\" align=\"center\"  width=\"120px\" height=\"113px\" onclick =\"insertSeatNo7()\">\r\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"120px\" height=\"113px\">\r\n");
      out.write("\t\t\t\t\t");
	if (list.get(7).getCondition() == 1) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/onseat08.jpg\" id =\"seat08\" align=\"center\"  width=\"120px\" height=\"113px\" onclick =\"insertSeatNo8()\">\r\n");
      out.write("\t\t\t\t\t");
	} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/offseat08.jpg\" id =\"seat08\" align=\"center\"  width=\"120px\" height=\"113px\"  onclick =\"insertSeatNo8()\">\r\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"120px\" height=\"113px\">\r\n");
      out.write("\t\t\t\t\t");
	if (list.get(8).getCondition() == 1) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/onseat09.jpg\" id =\"seat09\" align=\"center\"  width=\"120px\" height=\"113px\"  onclick =\"insertSeatNo9()\">\r\n");
      out.write("\t\t\t\t\t");
	} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/offseat09.jpg\" id =\"seat09\" align=\"center\"  width=\"120px\" height=\"113px\" onclick =\"insertSeatNo9()\">\r\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"120px\" height=\"113px\">\r\n");
      out.write("\t\t\t\t\t");
	if (list.get(9).getCondition() == 1) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/onseat10.jpg\" id =\"seat10\" align=\"center\"  width=\"120px\" height=\"113px\"  onclick =\"insertSeatNo10()\">\r\n");
      out.write("\t\t\t\t\t");
	} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/offseat10.jpg\" id =\"seat10\" align=\"center\"  width=\"120px\" height=\"113px\" onclick =\"insertSeatNo10()\">\r\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"120px\" height=\"113px\">\r\n");
      out.write("\t\t\t\t\t");
	if (list.get(10).getCondition() == 1) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/onseat11.jpg\" id =\"seat11\" align=\"center\"  width=\"120px\" height=\"113px\" onclick =\"insertSeatNo11()\">\r\n");
      out.write("\t\t\t\t\t");
	} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/offseat11.jpg\" id =\"seat11\" align=\"center\"  width=\"120px\" height=\"113px\" onclick =\"insertSeatNo11()\">\r\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"120px\" height=\"113px\">\r\n");
      out.write("\t\t\t\t\t");
	if (list.get(11).getCondition() == 1) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/onseat12.jpg\" id =\"seat12\" align=\"center\"  width=\"120px\" height=\"113px\" onclick =\"insertSeatNo12()\">\r\n");
      out.write("\t\t\t\t\t");
	} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/offseat12.jpg\" id =\"seat12\" align=\"center\"  width=\"120px\" height=\"113px\"  onclick =\"insertSeatNo12()\">\r\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"120px\" height=\"113px\">\r\n");
      out.write("\t\t\t\t\t");
	if (list.get(12).getCondition() == 1) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/onseat1.jpg\" id =\"seat13\" align=\"center\"  width=\"120px\" height=\"113px\" onclick =\"insertSeatNo13()\">\r\n");
      out.write("\t\t\t\t\t");
	} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/offseat13.jpg\" id =\"seat13\" align=\"center\"  width=\"120px\" height=\"113px\" onclick =\"insertSeatNo13()\">\r\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"120px\" height=\"113px\">\r\n");
      out.write("\t\t\t\t\t");
	if (list.get(13).getCondition() == 1) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/onseat14.jpg\" id =\"seat14\" align=\"center\"  width=\"120px\" height=\"113px\" onclick =\"insertSeatNo14()\">\r\n");
      out.write("\t\t\t\t\t");
	} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/offseat14.jpg\" id =\"seat14\" align=\"center\"  width=\"120px\" height=\"113px\" onclick =\"insertSeatNo14()\">\r\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"120px\" height=\"113px\">\r\n");
      out.write("\t\t\t\t\t");
	if (list.get(14).getCondition() == 1) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/onseat15.jpg\" id =\"seat15\" align=\"center\"  width=\"120px\" height=\"113px\"  onclick =\"insertSeatNo15()\">\r\n");
      out.write("\t\t\t\t\t");
	} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/offseat15.jpg\" id =\"seat15\" align=\"center\"  width=\"120px\" height=\"113px\" onclick =\"insertSeatNo15()\">\r\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"120px\" height=\"113px\">\r\n");
      out.write("\t\t\t\t\t");
	if (list.get(15).getCondition() == 1) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/onseat16.jpg\" id =\"seat16\" align=\"center\"  width=\"120px\" height=\"113px\"  onclick =\"insertSeatNo16()\">\r\n");
      out.write("\t\t\t\t\t");
	} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/offseat16.jpg\" id =\"seat16\" align=\"center\"  width=\"120px\" height=\"113px\"  onclick =\"insertSeatNo16()\">\r\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"120px\" height=\"113px\">\r\n");
      out.write("\t\t\t\t\t");
	if (list.get(16).getCondition() == 1) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/onseat17.jpg\" id =\"seat17\" align=\"center\"  width=\"120px\" height=\"113px\"  onclick =\"insertSeatNo17()\">\r\n");
      out.write("\t\t\t\t\t");
	} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/offseat17.jpg\" id =\"seat17\" align=\"center\"  width=\"120px\" height=\"113px\"  onclick =\"insertSeatNo17()\">\r\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"120px\" height=\"113px\">\r\n");
      out.write("\t\t\t\t\t");
	if (list.get(17).getCondition() == 1) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/onseat18.jpg\" id =\"seat18\" align=\"center\"  width=\"120px\" height=\"113px\"  onclick =\"insertSeatNo18()\">\r\n");
      out.write("\t\t\t\t\t");
	} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/offseat18.jpg\" id =\"seat18\" align=\"center\"  width=\"120px\" height=\"113px\"  onclick =\"insertSeatNo18()\">\r\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"120px\" height=\"113px\">\r\n");
      out.write("\t\t\t\t\t");
	if (list.get(18).getCondition() == 1) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/onseat19.jpg\"  id =\"seat19\" align=\"center\"  width=\"120px\" height=\"113px\"  onclick =\"insertSeatNo19()\">\r\n");
      out.write("\t\t\t\t\t");
	} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/offseat19.jpg\" id =\"seat19\" align=\"center\"  width=\"120px\" height=\"113px\"  onclick =\"insertSeatNo19()\">\r\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"120px\" height=\"113px\">\r\n");
      out.write("\t\t\t\t");
	if (list.get(19).getCondition() == 1) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/onseat20.jpg\" id =\"seat20\" align=\"center\"  width=\"120px\" height=\"113px\"  onclick =\"insertSeatNo20()\">\r\n");
      out.write("\t\t\t\t");
	} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/offseat20.jpg\" id =\"seat20\" align=\"center\"  width=\"120px\" height=\"113px\" onclick =\"insertSeatNo20()\">\r\n");
      out.write("\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"120px\" height=\"113px\">\r\n");
      out.write("\t\t\t\t\t");
	if (list.get(20).getCondition() == 1) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/onseat21.jpg\" id =\"seat21\" align=\"center\"  width=\"120px\" height=\"113px\"onclick =\"insertSeatNo21()\">\r\n");
      out.write("\t\t\t\t\t");
	} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/offseat21.jpg\" id =\"seat21\" align=\"center\"  width=\"120px\" height=\"113px\"onclick =\"insertSeatNo21()\">\r\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"120px\" height=\"113px\">\r\n");
      out.write("\t\t\t\t\t");
	if (list.get(21).getCondition() == 1) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/onseat22.jpg\" id =\"seat22\" align=\"center\"  width=\"120px\" height=\"113px\" onclick =\"insertSeatNo22()\">\r\n");
      out.write("\t\t\t\t\t");
	} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/offseat22.jpg\" id =\"seat22\" align=\"center\"  width=\"120px\" height=\"113px\"onclick =\"insertSeatNo22()\">\r\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"120px\" height=\"113px\">\r\n");
      out.write("\t\t\t\t\t");
	if (list.get(22).getCondition() == 1) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/onseat23.jpg\" id =\"seat23\" align=\"center\"  width=\"120px\" height=\"113px\" onclick =\"insertSeatNo23()\">\r\n");
      out.write("\t\t\t\t\t");
	} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/offseat23.jpg\" id =\"seat23\" align=\"center\"  width=\"120px\" height=\"113px\" onclick =\"insertSeatNo23()\">\r\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"120px\" height=\"113px\">\r\n");
      out.write("\t\t\t\t\t");
	if (list.get(23).getCondition() == 1) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/onseat24.jpg\" id =\"seat24\" align=\"center\"  width=\"120px\" height=\"113px\" onclick =\"insertSeatNo24()\">\r\n");
      out.write("\t\t\t\t\t");
	} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/offseat24.jpg\" id =\"seat24\" align=\"center\"  width=\"120px\" height=\"113px\" onclick =\"insertSeatNo24()\">\r\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"120px\" height=\"113px\">\r\n");
      out.write("\t\t\t\t\t");
	if (list.get(24).getCondition() == 1) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/onseat25.jpg\" id =\"seat25\" align=\"center\"  width=\"120px\" height=\"113px\" onclick =\"insertSeatNo25()\">\r\n");
      out.write("\t\t\t\t\t");
	} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/offseat25.jpg\" id =\"seat25\" align=\"center\"  width=\"120px\" height=\"113px\" onclick =\"insertSeatNo25()\">\r\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"120px\" height=\"113px\">\r\n");
      out.write("\t\t\t\t\t");
	if (list.get(25).getCondition() == 1) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/onseat26.jpg\" id =\"seat26\" align=\"center\"  width=\"120px\" height=\"113px\" onclick =\"insertSeatNo26()\">\r\n");
      out.write("\t\t\t\t\t");
	} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/offseat26.jpg\" id =\"seat26\" align=\"center\"  width=\"120px\" height=\"113px\"onclick =\"insertSeatNo26()\">\r\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"120px\" height=\"113px\">\r\n");
      out.write("\t\t\t\t\t");
	if (list.get(26).getCondition() == 1) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/onseat27.jpg\" id =\"seat28\" align=\"center\"  width=\"120px\" height=\"113px\" onclick =\"insertSeatNo27()\">\r\n");
      out.write("\t\t\t\t\t");
	} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/offseat27.jpg\" id =\"seat28\" align=\"center\"  width=\"120px\" height=\"113px\" onclick =\"insertSeatNo27()\">\r\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"120px\" height=\"113px\">\r\n");
      out.write("\t\t\t\t\t");
	if (list.get(27).getCondition() == 1) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/onseat28.jpg\" id =\"seat29\" align=\"center\"  width=\"120px\" height=\"113px\"onclick =\"insertSeatNo28()\">\r\n");
      out.write("\t\t\t\t\t");
	} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/offseat28.jpg\" id =\"seat29\" align=\"center\"  width=\"120px\" height=\"113px\"onclick =\"insertSeatNo28()\">\r\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"120px\" height=\"113px\">\r\n");
      out.write("\t\t\t\t\t");
	if (list.get(28).getCondition() == 1) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/onseat29.jpg\" id =\"seat29\" align=\"center\"  width=\"120px\" height=\"113px\"onclick =\"insertSeatNo29()\">\r\n");
      out.write("\t\t\t\t\t");
	} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/offseat29.jpg\" id =\"seat29\" align=\"center\"  width=\"120px\" height=\"113px\"onclick =\"insertSeatNo29()\">\r\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"120px\" height=\"113px\">\r\n");
      out.write("\t\t\t\t\t");
	if (list.get(29).getCondition() == 1) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/onseat30.jpg\" id =\"seat30\" align=\"center\"  width=\"120px\" height=\"113px\"onclick =\"insertSeatNo30()\">\r\n");
      out.write("\t\t\t\t\t");
	} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<IMG SRC=\"seatImg/offseat30.jpg\" id =\"seat30\" align=\"center\"  width=\"120px\" height=\"113px\"onclick =\"insertSeatNo30()\">\r\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
